### ISSUE TITLE
bug: createDnsRecord throws "undefined method `end_with?' for nil:NilClass"

### ISSUE THREAD

**Issue by CanRau** [netlify/js-client#107]
**- Do you want to request a *feature* or report a *bug*?**
This is a **bug** report

**- What is the current behavior?**
Trying to create DNS records using
```js
const NetlifyAPI = require("netlify");
const client = new NetlifyAPI("TOKE");
(async () => {
  const dnsZone = await client.getDNSForSite({
    site_id: "SITE_ID",
  });
  await client.createDnsRecord({
    zone_id: dnsZone[0].id,
    type: record.type,
    hostname: record.name,
    value: record.value,
  });
})();
```
throws the following error
```
ERROR: JSONHTTPError: Internal Server Error
    at parseResponse ([..]/node_modules/netlify/src/methods/response.js:12:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async callMethod ([..]/node_modules/netlify/src/methods/index.js:38:26)
    at async [..]/netlify-create-dns.js:17:7 {
  name: 'JSONHTTPError',
  status: 500,
  json: { error: "undefined method `end_with?' for nil:NilClass" }
}
```

It's already been brought up in the [community](https://community.netlify.com/t/netlify-api-for-adding-dns-record/805/3)

**- If the current behavior is a bug, please provide the steps to reproduce.**
Using the code from above using a valid API token and correct site id found in `https://app.netlify.com/sites/SITE_NAME/settings/general -> Site Information: APP ID`

**- What is the expected behavior?**
Creation of DNS records.

**- Please mention your node.js, and operating system version.**
NodeJS v12.14.1, macOS 10.14.6

**Comment by ehmicky** [comment]
Related: https://github.com/netlify/open-api/issues/240

**Comment by ehmicky** [comment]
Hi @CanRau,

Could you please try to send the same request but directly via HTTP (e.g. with `curl` or other similar tools) as suggested in https://github.com/netlify/open-api/issues/240?

This would allow making sure this is an API bug (which it seems to be) and not a bug in `js-client`. Thanks!

**Comment by CanRau** [comment]
Sure 🤝
I copy pasted the example from https://github.com/netlify/open-api/issues/240#issue-646761932, replaced API token & DNS zone id and received the same error
```
{"error":"undefined method `end_with?' for nil:NilClass"}
```

**Comment by ehmicky** [comment]
Thanks @CanRau.

I am forwarding this to our API team.

@vbrown608 @kitop @keiko713 Do you know what the problem might be?

**Comment by CanRau** [comment]
Sounds reasonable 😊👌

**Comment by kitop** [comment]
I'll file a bug on API.

I'm curious to see the value of `hostname: record.name,` that was sent in the original report.

For the one copied from open-api issue, did you set the `Content-Type`  to `application/json`? That's missing in the original curl example in the issue.

**Comment by kitop** [comment]
We deployed fix to API now that handles this. You should get a more helpful error message now.

@CanRau Can you please try again and let us know?

**Comment by CanRau** [comment]
Looks great 👏
cURL without content type header responds now with more useful error 
```
{"errors":{"type":["can't be blank","record type  is unsupported for api provider ns1"],"hostname":["can't be blank"],"value":["can't be blank"]}}
```
even though it wasn't directly clear to me that it's related to the content type 😅

With the content type set
```bash
curl -H 'Authorization: Bearer [API_TOKEN]' -H "Content-Type: application/json" \
     --data \
     '{"type":"A",
       "hostname":"junk.example.net",
       "value":"192.168.0.1",
       "ttl":3600,
       "priority":null,
       "weight":null,
       "port":null,
       "flag":null,
       "tag":null}' \
     https://api.netlify.com/api/v1/dns_zones/[ZONE_ID]/dns_records/
```
it works as expected and returns the result correctly
```json
{"hostname":"junk.example.net.gaiama.org","type":"A","ttl":3600,"priority":null,"weight":null,"port":null,"flag":null,"tag":null,"id":"[ID]","site_id":null,"dns_zone_id":"[ZONE_ID]","errors":[],"managed":false,"value":"192.168.0.1"}
```

can't get the js client working though, even after updating to `4.3.5`
```js
client.createDnsRecord({
  zone_id: dnsZone[0].id,
  type: record.type,
  hostname: record.name,
  value: record.value,
});
```
feeding it those values
```json
{
    "type": "A",
    "name": "TEST",
    "value": "192.168.0.1"
}
```
resulting in the following error
```
JSONHTTPError: Unprocessable Entity
    at parseResponse ([..]/node_modules/netlify/src/methods/response.js:12:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async callMethod ([..]/node_modules/netlify/src/methods/index.js:36:26)
    at async [..]/netlify-create-dns.js:21:7 {
  name: 'JSONHTTPError',
  status: 422,
  json: {
  "errors": {
    "type": [
      "can't be blank",
      "record type  is unsupported for api provider ns1"
    ],
    "hostname": [
      "can't be blank"
    ],
    "value": [
      "can't be blank"
    ]
  }
}
}
```
I logged all values and all are valid strings 🤷‍♂️
